# This is a basic workflow to help you define workflow variables

name: Workflow varibales in Single workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  name: Saibaba

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say Hello to saibaba
        run: echo $Greeting, world $name !
